gally:
    configuration:
        groups:
            index:
                labelKey: 'gally_configuration.group.index.label'
                position: 20
                scopeType: !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALIZED_CATALOG               
                fieldsets:
                    general:
                        labelKey: 'gally_configuration.group.index.fieldset.general.label'
                        position: 10
                        fields:
                            gally.indices_settings.prefix:
                                labelKey: 'gally_configuration.gally_indices_settings_prefix.label'
                                position: 10
                                input: 'string'
                            gally.indices_settings.timestamp_pattern:
                                labelKey: 'gally_configuration.gally_indices_settings_timestamp_pattern.label'
                                position: 10
                                input: 'string'
                            gally.indices_settings.number_of_shards:
                                labelKey: 'gally_configuration.gally_indices_settings_number_of_shards.label'
                                position: 10
                                input: 'number'
                            gally.indices_settings.number_of_replicas:
                                labelKey: 'gally_configuration.gally_indices_settings_number_of_replicas.label'
                                position: 10
                                input: 'number'
                            gally.indices_settings.time_before_ghost:
                                labelKey: 'gally_configuration.gally_indices_settings_time_before_ghost.label'
                                infoTooltipKey: 'gally_configuration.gally_indices_settings_time_before_ghost.tooltip'
                                position: 10
                                input: 'number'
                    ism:
                        labelKey: 'gally_configuration.group.index.fieldset.ism.label'
                        position: 20
                        fields:
                            gally.ism_settings.prefix:
                                labelKey: 'gally_configuration.gally_ism_settings_prefix.label'
                                position: 20
                                input: 'string'
                            gally.ism_settings.rollover_after:
                                labelKey: 'gally_configuration.gally_ism_settings_rollover_after.label'
                                position: 21
                                input: 'number'
                            gally.ism_settings.delete_after:
                                labelKey: 'gally_configuration.gally_ism_settings_delete_after.label'
                                infoTooltipKey: 'gally_configuration.gally_ism_settings_delete_after.tooltip'
                                position: 22
                                input: 'number'
                    template:
                        labelKey: 'gally_configuration.group.index.fieldset.template.label'
                        position: 30
                        fields:
                            gally.index_template_settings.prefix:
                                labelKey: 'gally_configuration.gally_index_template_settings_prefix.label'
                                position: 30
                                input: 'string'
