services:
    Gally\Doctrine\Filter\SearchColumnsFilter:
        arguments: [ '@doctrine', ~, '@?logger' ]
        tags: [ 'api_platform.filter' ]

    Gally\Doctrine\Filter\BooleanFilter:
        arguments: [ '@doctrine', ~, '@?logger' ]
        tags: [ 'api_platform.filter' ]

    Gally\Doctrine\Filter\JsonFilter:
        arguments: [ '@doctrine', ~, '@?logger' ]
        tags: [ 'api_platform.filter' ]
        
    Gally\Doctrine\Service\EntityManagerFactory:
        arguments: [ '@doctrine' ]

