framework:
    messenger:
        transports:
            tracking:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                options:
                    queue_name: tracking

        routing:
            'Gally\Tracker\Entity\TrackingEvent': tracking
